### ISSUE TITLE
Ring of Haste & Ring of Gaia have the same recip

### ISSUE THREAD

**Issue by TimelessRebornMC** [MasterEnderman/Divine-Equilibrium#4]
![2019-07-01_10 45 21](https://user-images.githubusercontent.com/52262808/60456199-7db3ca80-9bed-11e9-8a95-87431d1fab51.png)

**Comment by MasterEnderman** [comment]
Are you sure? Last time I checked they both had their own recipe? (also there are two pages in your jei, maybe check if it is shown there because technically the rings are the same item just with different nbt data, so if you click on one ring it should show the recipes for all rings that uses this item as a base)
